# Setting-up Oil and Gas Data

In [2]:
import pandas as pd

df = pd.read_csv("../../Data/Monday_Combined_dataset.csv")

df["date"] = pd.to_datetime(df["date"])
df = df.sort_values("date").set_index("date")

df = df.rename(columns={
    "gas_price": "gas_austin",
    "national_gas_price": "gas_us",
    "wti_price": "wti"
})

df.head()

,gas_austin,wti,gas_us
date,,,
2021-04-19,2.491,63.33,2.855
2021-04-26,2.475,62.02,2.872
2021-05-03,2.481,64.46,2.890
2021-05-10,2.563,64.92,2.961
2021-05-17,2.693,66.24,3.028


# Granger Causality Check 

In [5]:
from statsmodels.tsa.stattools import grangercausalitytests

# Use Monday-aligned dataset already loaded as df
# Columns should be: gas_austin, gas_us, wti

df_gc_austin = df[["gas_austin", "wti"]].diff().dropna()

print(df_gc_austin.head())

            gas_austin   wti
date                        
2021-04-26      -0.016 -1.31
2021-05-03       0.006  2.44
2021-05-10       0.082  0.46
2021-05-17       0.130  1.32
2021-05-24      -0.015 -0.11


In [10]:
print("WTI -> Austin Gas")
grangercausalitytests(df_gc_austin[["gas_austin", "wti"]], maxlag=4, verbose=True)

print("Austin Gas -> WTI")
grangercausalitytests(df_gc_austin[["wti", "gas_austin"]], maxlag=4, verbose=True)

WTI -> Austin Gas

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=72.5548 , p=0.0000  , df_denom=257, df_num=1
ssr based chi2 test:   chi2=73.4017 , p=0.0000  , df=1
likelihood ratio test: chi2=64.6533 , p=0.0000  , df=1
parameter F test:         F=72.5548 , p=0.0000  , df_denom=257, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=50.0428 , p=0.0000  , df_denom=254, df_num=2
ssr based chi2 test:   chi2=102.0558, p=0.0000  , df=2
likelihood ratio test: chi2=86.0410 , p=0.0000  , df=2
parameter F test:         F=50.0428 , p=0.0000  , df_denom=254, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=33.1592 , p=0.0000  , df_denom=251, df_num=3
ssr based chi2 test:   chi2=102.2519, p=0.0000  , df=3
likelihood ratio test: chi2=86.1317 , p=0.0000  , df=3
parameter F test:         F=33.1592 , p=0.0000  , df_denom=251, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=24

{np.int64(1): ({'ssr_ftest': (np.float64(0.2193983925892106),
    np.float64(0.6398957158274323),
    np.float64(257.0),
    np.int64(1)),
   'ssr_chi2test': (np.float64(0.22195946331982394),
    np.float64(0.6375509444697307),
    np.int64(1)),
   'lrtest': (np.float64(0.22186477489162826),
    np.float64(0.6376227121421592),
    np.int64(1)),
   'params_ftest': (np.float64(0.21939839258918878),
    np.float64(0.639895715827449),
    np.float64(257.0),
    1.0)},
   array([[0., 1., 0.]])]),
 np.int64(2): ({'ssr_ftest': (np.float64(2.717091251864799),
    np.float64(0.06798732598234455),
    np.float64(254.0),
    np.int64(2)),
   'ssr_chi2test': (np.float64(5.541154600259708),
    np.float64(0.0626258403985231),
    np.int64(2)),
   'lrtest': (np.float64(5.482711804815608),
    np.float64(0.06448285513289176),
    np.int64(2)),
   'params_ftest': (np.float64(2.71709125186476),
    np.float64(0.06798732598234719),
    np.float64(254.0),
    2.0)},
   array([[0., 0., 1., 0., 0.],
      

In [7]:
df_gc_us = df[["gas_us", "wti"]].diff().dropna()

print("WTI -> U.S. Gas")
grangercausalitytests(df_gc_us[["gas_us", "wti"]], maxlag=4, verbose=True)

print("U.S. Gas -> WTI")
grangercausalitytests(df_gc_us[["wti", "gas_us"]], maxlag=4, verbose=True)

WTI -> U.S. Gas

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=39.5951 , p=0.0000  , df_denom=257, df_num=1
ssr based chi2 test:   chi2=40.0573 , p=0.0000  , df=1
likelihood ratio test: chi2=37.2559 , p=0.0000  , df=1
parameter F test:         F=39.5951 , p=0.0000  , df_denom=257, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=22.0619 , p=0.0000  , df_denom=254, df_num=2
ssr based chi2 test:   chi2=44.9924 , p=0.0000  , df=2
likelihood ratio test: chi2=41.4853 , p=0.0000  , df=2
parameter F test:         F=22.0619 , p=0.0000  , df_denom=254, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=14.6785 , p=0.0000  , df_denom=251, df_num=3
ssr based chi2 test:   chi2=45.2635 , p=0.0000  , df=3
likelihood ratio test: chi2=41.7037 , p=0.0000  , df=3
parameter F test:         F=14.6785 , p=0.0000  , df_denom=251, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=12.3

{np.int64(1): ({'ssr_ftest': (np.float64(1.1076999549547344),
    np.float64(0.293571019218476),
    np.float64(257.0),
    np.int64(1)),
   'ssr_chi2test': (np.float64(1.1206303046234667),
    np.float64(0.28978277354149745),
    np.int64(1)),
   'lrtest': (np.float64(1.1182221980093345),
    np.float64(0.2903015829540878),
    np.int64(1)),
   'params_ftest': (np.float64(1.1076999549547968),
    np.float64(0.29357101921846246),
    np.float64(257.0),
    1.0)},
   array([[0., 1., 0.]])]),
 np.int64(2): ({'ssr_ftest': (np.float64(3.936365783114168),
    np.float64(0.020721284078432628),
    np.float64(254.0),
    np.int64(2)),
   'ssr_chi2test': (np.float64(8.027706597059602),
    np.float64(0.018063656300355207),
    np.int64(2)),
   'lrtest': (np.float64(7.905809587944304),
    np.float64(0.01919885198906642),
    np.int64(2)),
   'params_ftest': (np.float64(3.9363657831141365),
    np.float64(0.020721284078433273),
    np.float64(254.0),
    2.0)},
   array([[0., 0., 1., 0., 0.],
 

## Granger Results Summary

Granger Results Summary (Austin vs U.S.)

WTI → Austin Gas  
All lags: p = 0.0000  
Strong significance  

WTI → U.S. Gas  
All lags: p = 0.0000  
Strong significance  

Austin Gas → WTI  
p-values:  
lag 1: not significant  
lag 2: marginal  
lag 3: weak significance  
lag 4: not significant  
Overall weak and inconsistent  

U.S. Gas → WTI  
p-values:  
lag 1: not significant  
lag 2: ~0.02  
lag 3: ~0.05  
lag 4: not significant  
Weak significance, not consistent  

The results show strong and consistent evidence that oil prices Granger-cause both Austin and U.S. gasoline prices across all lag lengths. The reverse direction is weaker and inconsistent for both markets. While there is some evidence that gasoline prices may Granger-cause oil prices at certain lags, this likely reflects shared market dynamics rather than a true causal relationship. Overall, both Austin and U.S. gasoline markets appear to respond to oil price movements rather than influence them.

# Cointegration test

In [ ]:
from statsmodels.tsa.stattools import coint

# Austin gas and WTI
coint_austin = coint(df["gas_austin"], df["wti"])

print("Austin Gas + WTI")
print("Test stat:", coint_austin[0])
print("p-value:", coint_austin[1])
print("Critical values:", coint_austin[2])  

print("\n")

# U.S. gas and WTI
coint_us = coint(df["gas_us"], df["wti"])

print("U.S. Gas + WTI")
print("Test stat:", coint_us[0])
print("p-value:", coint_us[1])
print("Critical values:", coint_us[2])

Austin Gas + WTI
Test stat: -3.765469357171016
p-value: 0.01506167431257889
Critical values: [-3.93889347 -3.3596405  -3.06073974]


U.S. Gas + WTI
Test stat: -4.273575615009866
p-value: 0.0028141984724196815
Critical values: [-3.93889347 -3.3596405  -3.06073974]


p = 0.01 < 0.05 → reject null

-> There IS cointegration

The cointegration test indicates a long-run equilibrium relationship between oil and gasoline prices. Combined with strong Granger causality from oil to gasoline prices, this suggests that a Vector Error Correction Model (VECM) is appropriate to capture both short-run dynamics and long-run equilibrium behavior.